version: '2'
services:
  app:
    image: 'animal-inventory'
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    ports:
    - 8081:8081
    entrypoint: ["bash", "-c", "dockerize -wait tcp://db:5432 -wait tcp://config:8888 -timeout 60s && java org.springframework.boot.loader.JarLauncher"]

  config:
    image: 'config-server'
    container_name: config-server

  db:
    image: 'postgres:11-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres