server:
  port: 8081
spring:
  application:
    name: animal-inventory
  profiles:
    active: dev
  cloud:
    config:
      uri: http://config:8888
      username: root
      password: s3cr3t
  config:
    import: configserver:http://config:8888/